### ISSUE TITLE
Tasty-plutus tests

### ISSUE THREAD

**Issue by samuelWilliams99** [mlabs-haskell/majority-multisign#3]
This task is to write [tasty-plutus](https://github.com/Liqwid-Labs/plutus-extra/tree/master/tasty-plutus) tests for this project.
(Make sure you're using the `liqwid-labs` version of the repo, other `plutus-extra` versions do not have the functions needed. You may need to change the version the project is currently using).

Tasty plutus tests work directly against the validator, so you'll need to test the two redeemers supported.
The tests will need to check the signing behaviour and the datum updating behaviour.
It's likely not worth testing for >10 accepted signers, as we'll usually be using it in a 5 signer mode, 3 needed.

Feel free to branch off of `sam/initial-contracts` before it is merged, I dont expect there to be many behavioural changes. I'll let you know if you'll need to rebase.

**Comment by blamario** [comment]
This is all done.
